### ISSUE TITLE
delphi_android_system_bars: Android 6 = frozen splash screen

### ISSUE THREAD

**Issue by kazuser** [viniciusfbb/fmx_tutorials#1]
Hi! Thanks a lot!

Works fine on Android 9 but on Android 6 freezes on splash screen:
![Untitled](https://user-images.githubusercontent.com/3335273/115676248-3625a200-a371-11eb-8c4c-53c2adc109f1.png)

![Screenshot_2021-04-22-13-41-05](https://user-images.githubusercontent.com/3335273/115676286-4047a080-a371-11eb-8455-2232be245ac6.png)

![Screenshot_2021-04-22-13-38-59](https://user-images.githubusercontent.com/3335273/115676291-42116400-a371-11eb-8804-26bbab5ea5b4.png)

Here is my test-project: [Project1.zip](https://github.com/viniciusfbb/fmx_tutorials/files/6356475/Project1.zip)

**Comment by kazuser** [comment]
Nexus 7 (2013) — the same :(

![Screenshot_20210422-135732](https://user-images.githubusercontent.com/3335273/115681328-3d02e380-a376-11eb-9af0-6c1e81bd36e9.png)

**Comment by viniciusfbb** [comment]
Thanks for the report!

Fixed.

**Comment by kazuser** [comment]
Fixed, thanks a lot!

Last one: how to remove gray (non-transparent as I see) status-bar background when app loading?

![изображение](https://user-images.githubusercontent.com/3335273/115965678-0e3e6600-a54c-11eb-87f6-a0ad0dd35702.png)

**Comment by viniciusfbb** [comment]
The second part of the tutorial explain this: changing the background of the system bars in splash screen (launch screen). See:

https://github.com/viniciusfbb/fmx_tutorials/tree/master/delphi_android_system_bars/#splash-screen---system-bars-and-background

**Comment by kazuser** [comment]
Thank you!

BTW, works perfectly now even on first Nexus 7 (2012) with Android 5.1.1 (API 22):

![device-2021-04-25-085443](https://user-images.githubusercontent.com/3335273/115978885-58533600-a5a4-11eb-990e-d21b1f771f97.png)

![device-2021-04-25-085455](https://user-images.githubusercontent.com/3335273/115978890-5be6bd00-a5a4-11eb-9774-87a5bcc31a35.png)
