### ISSUE TITLE
About NatigationBar

### ISSUE THREAD

**Issue by jiangwei7480** [viniciusfbb/fmx_tutorials#12]
Hello
    I use it in D11，but NavtigationBarBackgroundColor not Effect
   Form1.SystemBars.NavigationBarBackgroundColor := TAlphaColors.Black;

**Comment by viniciusfbb** [comment]
Hi, what is the visibility property? (Form1.SystemBars.Visibility)

What kind of bottom bar does your android have? NavigationBar or GestureBar?

**Comment by viniciusfbb** [comment]
The GestureBar doesn’t have backgroundColor. Is it the ‘problem’?

**Comment by jiangwei7480** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello
             I'm very glad to hear your reply. My use environment is D11 and my mobile phone is Android12. The problem is that the background color of the navigation bar does not work.    The setting statement is as follows:    Form1.SystemBars.StatusBarBackgroundColor := TAlphaColors.Black;       Form1.SystemBars.NavigationBarBackgroundColor := TAlphaColors.Black;
    
           problem is NavigationBarBackgroundColor of property , Not Effect.   I took a look at your source code unit, which defines TAndroid11, this is the highest version, may need to add TAndroid12 definition.
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Vinícius Felipe Botelho ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/7/2022 01:04
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [viniciusfbb/fmx_tutorials] About NatigationBar (Issue #12)
        
      
    
  
  

The GestureBar doesn’t have backgroundColor. Is it the ‘problem’?

**Comment by viniciusfbb** [comment]
@jiangwei7480 I'm asking you about the bar type because there are two types of bars at the bottom:
1. NavigationBar (bar with the buttons: back, home and apps)
2. GestureBar (single bar)

See the screenshot:

![image](https://user-images.githubusercontent.com/11139086/188764020-6661755d-95a4-4594-9496-ce985dec5afc.png)


If your Android has a GestureBar, you can't change the background, the background is always transparent, but you can put a TRectangle at the bottom of the form with the color you want. Tip: You can also check the bar height with the insets property.

If your android is configured to use NavigationBar then the background color change should work and it's definitely a bug.

I've already tested it on emulated Android 12 and had no problems, but I've never tested it on physical Android 12, but it is expected to work as apparently there were no API changes from Android11 to Android 12.

What is the model and manufacturer of your device?

**Comment by jiangwei7480** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello
           My phone  is Samsung Mobile, type is Note20U
                 
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Vinícius Felipe Botelho ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/7/2022 08:42
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [viniciusfbb/fmx_tutorials] About NatigationBar (Issue #12)
        
      
    
  
  
@jiangwei7480 I'm asking you about the bar type because there are two types of bars at the bottom:

NavigationBar (bar with the buttons: back, home and apps)
GestureBar (single bar)

See the screenshot:

If your Android has a GestureBar, you can't change the background, the background is always transparent, but you can put a TRectangle at the bottom of the form with the color you want. Tip: You can also check the bar height with the insets property.
If your android is configured to use NavigationBar then the background color change should work and it's definitely a bug.
I've already tested it on emulated Android 12 and had no problems, but I've never tested it on physical Android 12, but it is expected to work as apparently there were no API changes from Android11 to Android 12.
What is the model and manufacturer of your device?

**Comment by jiangwei7480** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello
              Mobile phone status bar can achieve translucent，above graphic
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/7/2022 09:20
        
      
      
        
         To 
        
        
         
          
            ***@***.******@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [viniciusfbb/fmx_tutorials] About NatigationBar (Issue #12)
        
      
    
  
  

    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello
           My phone  is Samsung Mobile, type is Note20U
                 
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Vinícius Felipe Botelho ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/7/2022 08:42
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [viniciusfbb/fmx_tutorials] About NatigationBar (Issue #12)
        
      
    
  
  
@jiangwei7480 I'm asking you about the bar type because there are two types of bars at the bottom:

NavigationBar (bar with the buttons: back, home and apps)
GestureBar (single bar)

See the screenshot:

If your Android has a GestureBar, you can't change the background, the background is always transparent, but you can put a TRectangle at the bottom of the form with the color you want. Tip: You can also check the bar height with the insets property.
If your android is configured to use NavigationBar then the background color change should work and it's definitely a bug.
I've already tested it on emulated Android 12 and had no problems, but I've never tested it on physical Android 12, but it is expected to work as apparently there were no API changes from Android11 to Android 12.
What is the model and manufacturer of your device?

**Comment by viniciusfbb** [comment]
Translucent statusbar:
```delphi
  Form1.SystemBars.StatusBarBackgroundColor := $50000000;
  Form1.SystemBars.Visibility := TipFormSystemBars.TVisibilityMode.VisibleAndOverlap;
```

**Comment by viniciusfbb** [comment]
> Hello    My phone  is Samsung Mobile, type is Note20U

Can you send a screenshot of the problem?

**Comment by jiangwei7480** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello
          My phone ScreenHot



    
        

            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Vinícius Felipe Botelho ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/12/2022 20:46
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [viniciusfbb/fmx_tutorials] About NatigationBar (Issue #12)
        
      
    
  
  
Translucent statusbar:
  Form1.SystemBars.StatusBarBackgroundColor := $50000000;
  Form1.SystemBars.Visibility := TipFormSystemBars.TVisibilityMode.VisibleAndOverlap;

**Comment by viniciusfbb** [comment]
Fixed the problem in last commit.
