### ISSUE TITLE
delphi_android_system_bars: what about notch-friendly?

### ISSUE THREAD

**Issue by kazuser** [viniciusfbb/fmx_tutorials#2]
https://betterprogramming.pub/making-notch-friendly-apps-for-android-75776272be5c

**Comment by viniciusfbb** [comment]
@kazuser Thanks for the report!

I don't have android with notch to test the behavior of the current code, but I believe it will work the same way. Remembering: the solution proposed here is for your app to extend freely at the bottom of the status bar and navigation bar, that is, the system bar will have a transparent background and be above your form, so you can place a control as a rectangle with a fixed color or even image in the background.

If you have tested it and it is not working correctly, you could attach a print.

**Comment by kazuser** [comment]
If you have Android 9 — you can [simulate a notch](https://www.addictivetips.com/android/simulate-a-notch-on-an-android-phone/) ;)
