### ISSUE TITLE
Navigation bar location (left, right or bottom)

### ISSUE THREAD

**Issue by viniciusfbb** [viniciusfbb/fmx_tutorials#4]
> Do you know if there is a way to know if the navigation bar is located
at the bottom of the screen or on the right side of the screen?
This changes depending on orientation of the device and on the device type
(i.e. phone vs. Tablet), and I would like to create a function that will
return the actual full-screen size, including the navigation bar region
(when I use screen.size.width and screen.size.height, they return the size
without the navigation bar size, even when configured at full-size on
Delphi).

_Originally posted by @kobygold in https://github.com/viniciusfbb/fmx_tutorials/issues/3#issuecomment-826030430_

**Comment by viniciusfbb** [comment]
When I have more time I have to search for a solution using Java to be able to port to Delphi, because it is not so trivial as the Status Bar can be located on the left, right or bottom, according to the android version, the screen size and rotation angle.

**Comment by kobygold** [comment]
Hi Vinicius,
Following your tip from the other thread:
> After the TAndroidSystemBars.RemoveSystemBarsBackground(TAlphaColors.White, TAlphaColors.White); in your TForm1.FormCreate, the form size will be the size of the screen, as if the form were in fullscreen mode (note: you don't need to change any form property)

That was exactly what I was looking for!
After calling in TForm1.FormCreate:
TAndroidSystemBars.RemoveSystemBarsBackground(TAlphaColors.White, TAlphaColors.White);
I get the precise screen size from the Form size, i.e.:
Form1.Width and Form1.Height

I wanted to know if the navigation bar is on the left/right/top to be able to calculate the correct size of the screen, including the bars, but the above already gives me the actual screen width and height, which is exactly what I wanted!

Thanks,
Koby

**Comment by viniciusfbb** [comment]
Fixed! The code was rewritted to detect the changes and to give the insets (size of all system side bars) instead of individually returning the size of each one (status bar, navigation bar and others). Please read the Readme carefully to implement the new code.
