### ISSUE TITLE
Wrong insets (second try)))

### ISSUE THREAD

**Issue by kazuser** [viniciusfbb/fmx_tutorials#7]
Hi, it's me again 😊

```
procedure TiForm.Button1Click(Sender: TObject);
begin
  Button1.Text := 'L:' + Trunc(iForm.SystemBars.Insets.Left * TAndroidHelper.DisplayMetrics.scaledDensity).ToString +
               ' / T:' + Trunc(iForm.SystemBars.Insets.Top * TAndroidHelper.DisplayMetrics.scaledDensity).ToString +
               ' / R:' + Trunc(iForm.SystemBars.Insets.Right * TAndroidHelper.DisplayMetrics.scaledDensity).ToString +
               ' / B:' + Trunc(iForm.SystemBars.Insets.Bottom * TAndroidHelper.DisplayMetrics.scaledDensity).ToString + #13#10 +

                  'L:' + AView.NativeView.getRootWindowInsets.getStableInsetLeft.ToString +
               ' / T:' + AView.NativeView.getRootWindowInsets.getStableInsetTop.ToString +
               ' / R:' + AView.NativeView.getRootWindowInsets.getStableInsetRight.ToString +
               ' / B:' + AView.NativeView.getRootWindowInsets.getStableInsetBottom.ToString;
end;
```

![IMG_2599](https://user-images.githubusercontent.com/3335273/132112797-1edeaa3f-40ff-49d5-8d3d-8d63baa12abe.jpg)

I think I need your help :(

Android 11: getStableInsetX works fine but it is [deprecated](https://developer.android.com/reference/android/view/WindowInsets#getStableInsetBottom()) now. What can replace it?

Here is my sample project: [test insets.zip](https://github.com/viniciusfbb/fmx_tutorials/files/7110786/test.insets.zip)

**Comment by kazuser** [comment]
BTW, that cutout enabled programmatically in Developer Options: 

![device-2021-09-05-081003](https://user-images.githubusercontent.com/3335273/132112867-e50a32b4-92ac-4dc5-82ab-5f88c2591b05.png)

**Comment by viniciusfbb** [comment]
I think you edited the source again... It wasn't for the cutout to go in from the left or the right... The answer is really zero but it should be totally black like in that chrome screenshoot, remember?

https://github.com/viniciusfbb/fmx_tutorials/issues/6#issuecomment-901113811

**Comment by kazuser** [comment]
Yep, source was edited (you can check it in my zip-file from my first message) but I really need it 😔

I thought that "getStableInsetX" could be replaced by something else (not deprecated).

**Comment by viniciusfbb** [comment]
Replace this line:

https://github.com/viniciusfbb/fmx_tutorials/blob/77429826f9010226b0a4d5a58b5b8f7f8cbc5b09/delphi_system_bars/iPub.FMX.SystemBars.Android.pas#L302

By:
```delphi
      function getInsets(typeMask: Integer): TAndroid10.JInsets; cdecl;
      function getInsetsIgnoringVisibility(typeMask: Integer): TAndroid10.JInsets; cdecl;
```

then you can use:

```delphi
  LInsets := LWindowInsetsAndroid11.getInsetsIgnoringVisibility(TAndroid11.TJWindowInsets_Type.JavaClass.systemBars);
  if Assigned(LInsets) then
    Result := TRect.Create(LInsets.left, LInsets.top, LInsets.right, LInsets.bottom)
  else
    Result := TRect.Empty;
```
