### ISSUE TITLE
Delphi 11 + Android 7

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciusfbb/fmx_tutorials#8]
Testando a sua biblioteca com o Delphi 11 não tive resultado com os androids 7 (asus), 8 (lg).
Apenas iniciei um app novo e adicionei as rotinas.

unit ufrmPrincipal;

interface

uses
  System.SysUtils, System.Types, System.UITypes, System.Classes, System.Variants,
  FMX.Types, FMX.Controls, FMX.Forms, FMX.Graphics, FMX.Dialogs,iPub.FMX.SystemBars;

type
  TfrmPrincipal = class(TForm)
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frmPrincipal: TfrmPrincipal;

implementation

{$R *.fmx}

procedure TfrmPrincipal.FormCreate(Sender: TObject);
begin
  frmPrincipal.SystemBars.StatusBarBackgroundColor := $20000000;
  frmPrincipal.SystemBars.NavigationBarBackgroundColor := $20000000;
  frmPrincipal.SystemBars.Visibility := TipFormSystemBars.TVisibilityMode.VisibleAndOverlap;
end;

end.

**Comment by viniciusfbb** [comment]
Alisson, vc pode anexar uma print? 

Uma dica: Prefiro usar barras 100% transparentes, sendo que a cor $00000000 forçará os ícones a ficarem brancos, enquanto que $00FFFFFF forçará os ícones a ficarem pretos. Daí eu uso o OnInsetsChange para ajustar o layout do form para evitar que os controles como botões fiquem abaixo das barras…

**Comment by alissonrodrigo** [comment]
![image](https://user-images.githubusercontent.com/8572209/150207779-ce725022-70c4-4791-a432-398a60859813.jpeg)

**Comment by viniciusfbb** [comment]
Estranho, aqui está funcionando até no Delphi 11 + Android 6:

![IMG_2524](https://user-images.githubusercontent.com/11139086/150209541-05458870-5555-4039-9f38-241a6fd89384.jpg)

Faz um teste pra mim? Tenta alterar o local da declaração, tente em outros dois lugares do form:

1) No evento OnShow, e caso não dê certo,
2) tente no constructor Create(AOwner: TComponent);

**Comment by alissonrodrigo** [comment]
Tenho que alterar a propriedade theme para NoTitleBar?

**Comment by viniciusfbb** [comment]
Não, use tudo padrão, projeto em branco mesmo.

**Comment by alissonrodrigo** [comment]
Estranho também está projeto padrão! Testei em 3 dispositivos versões diferentes e fabricantes diferentes

**Comment by alissonrodrigo** [comment]
Gostaria que eu envia-se o projeto para olhar?

**Comment by viniciusfbb** [comment]
Sim, incluindo a pasta dos binários do projeto

**Comment by alissonrodrigo** [comment]
Na verdade eu descobrir o motivo, porque de padrão sempre removo o splash do delphi
![image](https://user-images.githubusercontent.com/8572209/150332592-3e8158d8-3625-4fa8-ae65-5f652fc3e10a.png)
e crio uma própria tela para isso, então se eu habilitar o splash ao tudo funciona! Sabe como posso resolver?

**Comment by viniciusfbb** [comment]
Tem que ver. Mas por que vc quer remover o splash screen? Por mais que vc coloque um form inicial de splash pra depois chamar o seu real main form, terá um delay entre clicar no ícone e esse form de splash. Esse delay é o tempo do android carregar o app na memória RAM mais algumas inicializações, o que pode ser bem demorado em alguns devices. O mais correto é ajustar o splash screen e não removê-lo. Inclusive vc até pode manter seu form de splash screen, pois após a imagem estática da splashscreen, seu form poderia entrar com alguma animação de logo por exemplo (mas aí vc tem que conferir o alinhamento pra que os usuários não percebam a transição do splashscreen para o 'splash form').

Particularmente eu prefiro utilizar apenas a splashscreen estática mesmo pois os usuários não gostam de delays na abertura...

Além disso, embora a maioria não saiba, é possível personalizar totalmente a splashscreen, mesmo em aplicações feitas em delphi, incluindo personalizar cor de fundo, cor das barras, incluir sua logo em formato SVG (o que também pode ser feito com o ícone do app, eu até postei sobre o assunto no [DelphiPraxis](https://en.delphipraxis.net/topic/5228-androidfmx-which-solution-to-have-a-full-size-app-icon-with-android-10/?do=findComment&comment=45311), mas não vem ao caso).
Para isso é preciso fazer um trabalho manual, pelas configurações de projeto do delphi não é possível. Inclusive eu cheguei a postar no próprio readme deste projeto sobre algumas dessas customizações da splashscreen, confira: https://github.com/viniciusfbb/fmx_tutorials/tree/master/delphi_system_bars#android-splash-screen---system-bars-and-background

**Comment by alissonrodrigo** [comment]
Bem essa e uma pratica que carrego já do Delphi XE7, o splash não se enquadrava na tela toda, por isso peguei o caminha 'mais curto' e desenvolvi minhas proprias splash baseadas em forms 
procedure TfrmPrincipal.Splash;
begin

  TThread.CreateAnonymousThread(
    procedure
    var
      Logado: Boolean;
      sNivelAcesso, sIDAssociado, sIDFuncionario: string;
    begin
      
      Application.CreateForm(TdmRestClient, dmRestClient);
      Application.CreateForm(TdmRestLogin, dmRestLogin);
      Application.CreateForm(TdmRestToken, dmRestToken);
    
      Logado := dmUsuario.UsuarioLogado;

      TThread.Synchronize(TThread.CurrentThread,
        procedure
        begin
          if Logado = False then
            tabPrincipal.ActiveTab := TabItemLogin
          else
          begin
            if dmUsuario.qryUsuario.Active = False then
              dmUsuario.qryUsuario.Active := True;
            sNivelAcesso := dmUsuario.qryUsuario.FieldByName('nivel').AsString;

            if sNivelAcesso = 'Funcionario' then
            begin
              tabPrincipal.ActiveTab := TabItemAdministrador;
            end
            else if sNivelAcesso = 'Associado' then
            begin
              Application.CreateForm(TfrmPrincipalAssociado, frmPrincipalAssociado);
              Application.MainForm := frmPrincipalAssociado;
              frmPrincipalAssociado.Show;
              frmPrincipalAssociado.CarregaMinhasMovimentacoes;
              frmPrincipalAssociado.CarregarCompeticoes;
              Close;
            end;
          end;
        end);

    end).Start;

**Comment by viniciusfbb** [comment]
Alisson, essa não é uma boa opção. No seu código você está criando forms em background thread, não é correto, pode gerar crashs inesperados mais cedo ou mais tarde. Forms, components, UI no modo geral, utilize apenas no main thread.

Como te disse, sou a favor da splashscreen normal mesmo.

> o splash não se enquadrava na tela toda

Normal, há uma infinidade de aparelhos e cada um com tamanho diferente de tela, daí vc deve configurar o background color para ser o mesmo background color da sua imagem para parecer que ela está ocupando a tela inteira.

**Comment by alissonrodrigo** [comment]
Entendo, essa pratica eu peguei nesse 'tutorial' 
http://www.uweraabe.de/Blog/2016/01/22/a-splash-form-in-firemonkey/

Você pode me indicar uma documentação onde posso ler mais a respeito do splash do delphi?
Do link que me enviou onde você diz sobre os xml para icones e splash tem a possibilidade de usar svg e gradientes também parece muito interessante

**Comment by viniciusfbb** [comment]
Alisson, um ótimo ponto de partida é o readme deste repositório. Não há muita documentação na internet, pra não dizer nenhuma, de splashscreen para apps do firemonkey.

Mas o readme que fiz te ensina a alterar o background, as barras e a imagem.

Para adicionar o svg no lugar da imagem é mais trabalhoso, mas totalmente possível. Também é necessário fazer o passo a passo do readme, pq quando vc configurar tudo certo, com o seu próprio splash_image_def.xml funcionando, daí fica fácil fazer o svg. Neste ponto, basicamente vc terá que:

1) converter o seu .svg para um vetor xml que o Android suporta (vc pode usar o Android studio, ou simplesmente pegar um pronto e alterar a propriedade do path manualmente caso o seu svg seja um tipo simples).

2) salvar o .xml com o nome por exemplo "splash_vector.xml" e colocar no deployment para a mesma pasta do "splash_image_def.xml"

3) substitua novamente o conteúdo do "splash_image_def.xml" para:

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
  <item>
    <shape android:shape="rectangle">
      <solid android:color="#f44336" />
    </shape>
  </item>
  <item
	android:gravity="center"
	android:drawable="@drawable/splash_vector">
  </item>
</layer-list>
```

**Comment by viniciusfbb** [comment]
Um exemplo de vetor xml após a conversão de um svg:

```xml

<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="320dp"
    android:height="320dp"
    android:viewportWidth="320.0"
    android:viewportHeight="320.0">
    <path android:name="splash_logo_foreground"
        android:fillColor="#ffffffff"
        android:pathData="M 196.83,213.00
           C 191.85,213.00 189.74,209.62 189.74,209.62
             189.74,209.62 189.65,209.62 189.65,209.62
             189.65,209.62 189.69,210.27 189.69,211.23
             189.69,211.23 189.69,212.44 189.69,212.44
             189.69,212.44 184.11,212.44 184.11,212.44
             184.11,212.44 184.11,185.18 184.11,185.18
             184.11,184.48 183.73,184.15 183.07,184.15
             183.07,184.15 181.19,184.15 181.19,184.15
             181.19,184.15 181.19,179.07 181.19,179.07
             181.19,179.07 186.88,179.07 186.88,179.07
             189.08,179.07 190.02,180.06 190.02,182.27
             190.02,182.27 190.02,189.22 190.02,189.22
             190.02,190.40 189.93,191.24 189.93,191.24
             189.93,191.24 190.02,191.24 190.02,191.24
             190.02,191.24 192.18,187.91 197.20,187.91
             203.68,187.91 207.89,193.03 207.89,200.45
             207.89,208.07 203.17,213.00 196.83,213.00 Z
           M 195.89,193.03
           C 192.79,193.03 189.88,195.28 189.88,200.59
             189.88,204.31 191.81,207.97 195.80,207.97
             199.13,207.97 201.85,205.29 201.85,200.55
             201.85,196.00 199.41,193.03 195.89,193.03 Z
           M 181.49,212.44
           C 181.49,212.44 175.99,212.44 175.99,212.44
             173.93,212.44 172.86,211.45 172.86,209.76
             172.86,209.76 172.86,209.10 172.86,209.10
             172.86,208.54 172.89,208.02 172.89,208.02
             172.89,208.02 172.80,208.02 172.80,208.02
             171.67,210.51 168.67,213.00 164.54,213.00
             159.46,213.00 156.27,210.42 156.27,203.88
             156.27,203.88 156.27,194.58 156.27,194.58
             156.27,194.58 156.27,193.55 156.27,193.55
             156.27,193.55 156.27,191.70 156.27,191.70
             156.27,191.70 156.27,190.10 156.27,190.10
             156.27,190.10 156.27,188.47 156.27,188.47
             156.27,188.47 159.04,188.47 159.04,188.47
             161.25,188.47 162.19,189.46 162.19,191.62
             162.19,191.62 162.19,202.66 162.19,202.66
             162.19,205.58 162.99,207.55 165.90,207.55
             170.22,207.55 172.61,203.74 172.61,199.47
             172.61,199.47 172.61,188.47 172.61,188.47
             172.61,188.47 172.84,188.47 175.31,188.47
             177.77,188.47 178.50,189.47 178.54,191.70
             178.59,193.93 178.57,206.37 178.57,206.37
             178.57,207.03 178.95,207.41 179.61,207.41
             179.61,207.41 181.49,207.41 181.49,207.41
             181.49,207.41 181.49,212.44 181.49,212.44 Z
           M 141.73,200.92
           C 141.73,200.92 135.67,200.92 135.67,200.92
             135.67,200.92 135.67,212.44 135.67,212.44
             135.67,212.44 129.52,212.44 129.52,212.44
             129.52,212.44 129.52,184.29 129.52,184.29
             129.52,184.29 126.47,184.29 126.47,184.29
             126.47,184.29 126.47,179.07 126.47,179.07
             126.47,179.07 141.73,179.07 141.73,179.07
             147.99,179.07 152.34,183.44 152.34,189.93
             152.34,196.41 147.99,200.92 141.73,200.92 Z
           M 140.70,184.29
           C 140.70,184.29 135.67,184.29 135.67,184.29
             135.67,184.29 135.67,195.66 135.67,195.66
             135.67,195.66 140.60,195.66 140.60,195.66
             144.08,195.66 146.05,193.42 146.05,189.93
             146.05,186.50 144.08,184.29 140.70,184.29 Z
           M 115.91,209.24
           C 115.91,209.24 115.91,194.58 115.91,194.58
             115.91,193.88 115.54,193.55 114.88,193.55
             114.88,193.55 113.00,193.55 113.00,193.55
             113.00,193.55 113.00,188.47 113.00,188.47
             113.00,188.47 118.68,188.47 118.68,188.47
             120.89,188.47 121.83,189.46 121.83,191.67
             121.83,191.67 121.83,206.37 121.83,206.37
             121.83,207.03 122.23,207.41 122.86,207.41
             122.86,207.41 124.74,207.41 124.74,207.41
             124.74,207.41 124.74,212.44 124.74,212.44
             124.74,212.44 119.06,212.44 119.06,212.44
             116.85,212.44 115.91,211.50 115.91,209.24 Z
           M 116.19,179.07
           C 116.19,179.07 121.36,179.07 121.36,179.07
             121.36,179.07 121.36,184.57 121.36,184.57
             121.36,184.57 116.19,184.57 116.19,184.57
             116.19,184.57 116.19,179.07 116.19,179.07 Z
           M 178.30,98.58
           C 174.37,98.58 170.51,98.58 166.66,98.58
             162.80,98.58 158.95,98.58 155.06,98.58
             155.04,98.45 155.00,98.36 155.00,98.26
             155.00,97.71 154.99,97.16 155.01,96.61
             155.09,94.16 157.05,92.30 159.17,92.10
             159.50,92.06 159.84,92.03 160.17,92.03
             168.28,92.03 176.38,92.03 184.49,92.03
             184.68,92.03 184.88,92.03 185.05,92.03
             185.22,92.23 185.16,92.43 185.16,92.62
             185.17,94.40 185.16,96.19 185.16,97.98
             185.16,98.17 185.16,98.36 185.16,98.58
             185.34,98.60 185.47,98.62 185.61,98.62
             187.29,98.62 188.97,98.59 190.65,98.62
             193.41,98.68 195.65,99.79 197.33,101.99
             198.44,103.44 199.00,105.09 199.00,106.92
             199.01,109.19 199.01,111.45 199.01,113.72
             199.01,120.75 199.00,127.77 199.01,134.80
             199.01,137.12 198.54,139.34 197.50,141.41
             195.17,146.01 191.45,148.79 186.39,149.77
             186.20,149.80 186.01,149.82 185.81,149.85
             185.62,149.88 185.43,149.90 185.24,149.92
             185.11,150.11 185.17,150.31 185.17,150.50
             185.16,152.54 185.18,154.57 185.16,156.61
             185.14,158.61 184.49,160.40 183.14,161.89
             181.60,163.61 179.66,164.51 177.34,164.57
             177.18,164.57 177.02,164.57 176.86,164.57
             165.41,164.57 153.96,164.57 142.51,164.57
             141.65,164.57 140.82,164.50 139.99,164.27
             136.89,163.39 134.60,160.64 134.29,157.50
             134.25,157.09 134.22,156.69 134.22,156.28
             134.22,144.56 134.22,132.85 134.22,121.13
             134.22,120.95 134.22,120.78 134.22,120.56
             134.35,120.60 134.45,120.61 134.53,120.65
             136.63,121.67 138.72,121.67 140.82,120.65
             140.88,120.62 140.95,120.60 141.01,120.57
             141.03,120.57 141.05,120.58 141.11,120.59
             141.12,120.79 141.12,120.99 141.12,121.20
             141.12,129.18 141.12,137.16 141.12,145.15
             141.12,145.55 141.14,145.96 141.20,146.36
             141.50,148.36 143.22,149.86 145.24,149.91
             145.40,149.91 145.56,149.91 145.72,149.91
             155.06,149.91 164.41,149.91 173.75,149.91
             174.19,149.91 174.64,149.89 175.07,149.79
             176.92,149.36 178.24,147.71 178.29,145.80
             178.30,145.59 178.29,145.38 178.29,145.16
             178.29,129.89 178.29,114.62 178.29,99.34
             178.30,99.12 178.30,98.89 178.30,98.58 Z
           M 185.27,123.40
           C 185.27,129.10 185.27,134.80 185.27,140.50
             185.27,140.70 185.26,140.89 185.28,141.08
             185.31,141.45 185.51,141.72 185.85,141.86
             186.02,141.93 186.23,141.94 186.42,141.94
             189.05,141.94 191.50,140.16 192.40,137.62
             192.69,136.81 192.79,135.97 192.79,135.11
             192.78,130.32 192.79,125.52 192.79,120.72
             192.79,116.28 192.79,111.84 192.79,107.39
             192.79,107.18 192.79,106.97 192.77,106.76
             192.67,105.70 191.92,104.97 190.86,104.89
             190.74,104.88 190.62,104.88 190.49,104.88
             189.18,104.88 187.87,104.88 186.56,104.88
             186.44,104.88 186.31,104.88 186.19,104.89
             185.64,104.96 185.30,105.32 185.27,105.88
             185.26,106.05 185.27,106.23 185.27,106.41
             185.27,112.07 185.27,117.74 185.27,123.40 Z
           M 163.06,157.11
           C 163.02,155.09 161.46,153.53 159.47,153.53
             157.46,153.54 155.89,155.12 155.89,157.12
             155.90,159.11 157.46,160.70 159.48,160.70
             161.48,160.69 163.03,159.12 163.06,157.11 Z
           M 144.22,79.83
           C 145.95,76.24 148.65,73.59 152.40,72.10
             156.17,70.61 159.98,70.63 163.73,72.17
             167.47,73.70 170.13,76.38 171.84,80.05
             175.56,79.53 178.85,80.43 181.62,82.97
             183.27,84.48 184.72,87.02 184.85,88.56
             184.66,88.57 184.47,88.58 184.28,88.58
             182.41,88.58 180.53,88.58 178.66,88.58
             173.54,88.58 168.43,88.58 163.31,88.58
             162.11,88.58 160.91,88.58 159.70,88.60
             156.86,88.64 154.63,89.86 152.99,92.15
             152.00,93.54 151.53,95.12 151.53,96.84
             151.53,99.08 151.53,101.33 151.53,103.58
             151.53,104.08 151.46,104.56 151.26,105.03
             150.65,106.46 149.18,107.28 147.60,107.09
             146.15,106.91 144.94,105.73 144.70,104.25
             144.65,103.99 144.63,103.72 144.63,103.46
             144.62,102.43 144.62,101.40 144.63,100.38
             144.63,99.91 144.49,99.51 144.19,99.16
             143.69,98.60 143.05,98.46 142.35,98.65
             141.67,98.83 141.19,99.46 141.13,100.17
             141.11,100.34 141.12,100.52 141.12,100.70
             141.12,105.07 141.12,109.44 141.12,113.81
             141.11,114.18 141.09,114.55 141.00,114.91
             140.68,116.26 139.40,117.52 137.58,117.48
             135.93,117.44 134.56,116.24 134.29,114.62
             134.24,114.36 134.22,114.10 134.22,113.83
             134.22,105.55 134.22,97.27 134.22,88.99
             134.38,85.83 135.72,83.31 138.31,81.50
             139.89,80.40 141.67,79.87 143.61,79.88
             143.78,79.89 143.96,79.88 144.14,79.88
             144.15,79.88 144.17,79.86 144.22,79.83 Z" />
</vector>

```

**Comment by alissonrodrigo** [comment]
Desculpe reabrir mas passando apenas para agradecer. Já estou em processo de mudando do metodo antigo que usava para a solução que você disponibilizou.
Tentando contribuir um pouco para as pessoas que usam muiro gradientes e cores como nos usamos vai uma ferramenta online e gratuita para desenvolver os codigos xml usado no android
[angrytools.com/gradient/](https://angrytools.com/gradient/)
grato

**Comment by viniciusfbb** [comment]
Top! 👏🏻👏🏻

**Comment by viniciusfbb** [comment]
Lembrando que se você tem o svg pronto, pelo android studio ele converte facilmente para vetor xml:

Android Studio > Resource Manager > + > Vector Assets > 

![image](https://user-images.githubusercontent.com/11139086/150559309-ebcd10ef-1f75-4d6d-817e-510803cce7eb.png)

(choose svg file) > Next >

![image](https://user-images.githubusercontent.com/11139086/150559462-643c51e3-859b-47d5-ad6a-ea4ae212b6fa.png)

**Comment by alissonrodrigo** [comment]
Muito bom e as possibilidades abertas por trabalhos como e de vocês elevam o nivel dos apps desenvolvidos em delphi o Skia4Delphi e muito bom (aguardando a versão 3, kkk).
Estou pesquisando a documentação para replicar o gradiente no splash do IOS. se tiver alguma dica agradeço. 
Obrigado

**Comment by viniciusfbb** [comment]
O iOS é inflexível! Aceita apenas png, se algo mudou foi recente, mas até então só imagem estática mesmo. Mas se você encontrar algo novo, compartilhe aqui para ajudar outros...

**Comment by alissonrodrigo** [comment]
> 

Acho que fui vago, estou dizendo ao desenho do background (por padrão preto) que pode ser alterado no delphi .
![image](https://user-images.githubusercontent.com/8572209/150564191-5011d896-d25b-435f-b90b-5665e3774b4a.png)
Tem como personalizar e colocar gradiente?

**Comment by viniciusfbb** [comment]
Nunca me aventurei, tem que pesquisar. Eu te ajudaria, mas estou dedicando todo meu tempo ao outro projeto...

**Comment by alissonrodrigo** [comment]
Que isso não precisa obrigado! Já ajudou muito valeu
