### ISSUE TITLE
Margens das barras no Android não funciona

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciusfbb/fmx_tutorials#9]
procedure TfrmRegistraAssociado.FormShow(Sender: TObject);
var
  R: TRectF;
begin
  frmRegistraAssociado.SystemBars.StatusBarBackgroundColor := $00000000;
  frmRegistraAssociado.SystemBars.NavigationBarBackgroundColor := $00000000;
  frmRegistraAssociado.SystemBars.Visibility := TipFormSystemBars.TVisibilityMode.VisibleAndOverlap;
  R:= frmRegistraAssociado.SystemBars.Insets;
{$IFDEF iOS}
  lytBase.Margins.Top := 35;
{$ENDIF}
{$IFDEF ANDROID}
  lytBase.Margins.Top := R.Top;
  lytBase.Margins.Bottom:= R.Bottom;
  Padding.Rect := frmRegistraAssociado.SystemBars.Insets;
{$ENDIF}
end;

![image](https://user-images.githubusercontent.com/8572209/151035853-cad3d1c5-b035-46dc-914d-34ffd53bccfd.jpeg)

**Comment by viniciusfbb** [comment]
Alisson, as margens estão funcionando, o que não ajuda são as nomenclaturas, ficou um pouco confuso, mas segui exatamente as nomenclauras que das apis do android. 

Veja um exemplo de código que uso:

```pascal
procedure TForm1.FormCreate(Sender: TObject);
begin
  SystemBars.StatusBarBackgroundColor := $00FFFFFF; // Branco transparente (forçando os ícones escuros)
  SystemBars.NavigationBarBackgroundColor := $00FFFFFF; // Branco transparente (forçando os ícones escuros)
  SystemBars.Visibility := TFormSystemStatusBar.TVisibilityMode.VisibleAndOverlap;
  SystemBars.OnInsetsChange := SystemBarsInsetsChange;
  SystemBarsInsetsChange(nil);
end;

procedure TfrmBase.SystemBarsInsetsChange(Sender: TObject);
begin
  rctStatusBar.Height := Self.SystemBars.Insets.Top;
  rctNavigationBar.Height := Self.SystemBars.TappableInsets.Bottom;
  if HasBottomContent then
    rctGestureBar.Height := Self.SystemBars.Insets.Bottom - Self.SystemBars.TappableInsets.Bottom
  else
    rctGestureBar.Height := 0;
end;
```

Note a existência de 3 retangulos: rctStatusBar, rctNavigationBar, rctGestureBar. O design do código é por sua conta, mas particularmente eu prefiro ter sempre esses 3 retangulos no layout dos meus forms, alinhados MostTop, MostBottom, MostBottom respectivamente.

No exemplo que escrevi acima existe também uma função **HasBottomContent** que deixo no meu form base declarada como virtual (gosto de usar herança de forms). Daí o form que tem algum conteudo alinhado com o bottom, eu coloco o HasBottomContent True.
Isso é feito pq temos que considerar 2 layouts no android quando pensamos nas barras do sistema: o layout com NavigationBar e o layout com GestureBar. Na sua foto a barra do seu celular é um NavigationBar, então neste caso o normal é termos um fundo sempre opaco (que defino pela cor do rctNavigationBar). 

Porém quando consideramos GestureBar, que é a foto abaixo:
![gestureBar](https://user-images.githubusercontent.com/11139086/151050219-4f1b9636-2c0e-4708-bd87-80ba30cd067e.png)

o normal neste caso é fundo transparente (isto é, rctGestureBar.Height = 0), porém devemos evitar que controles (como botões) alinhados na parte de baixo, fiquem abaixo dela, por isso o rctGestureBar.Height será diferente de zero quando quando a barra for GestureBar e o HasBottomContent for true. Estes 3 retangulos são as margens do form que eu uso, sendo cada form responsável por definir as suas cores e informar se tem controles alinhados na parte de baixo.

Não sei se ficou claro, mas qualquer dúvida fique a vontade para perguntar.

**Comment by alissonrodrigo** [comment]
Fui compilar aqui com o exemplo usado por você e me reclamou um erro que a variavel não existe HasBottomContent

**Comment by viniciusfbb** [comment]
Eu mencionei na explicação acima. É uma função que declaro em meus forms (pode ser variável também), que o seu form deve informar True quando tiver algum controle alinhado na parte de baixo (como um botão) e False caso contrário.

**Comment by viniciusfbb** [comment]
Bem, para tentar ser mais claro, segue o código todo deste exemplo:

```pascal
unit Unit1;

interface

uses
  System.SysUtils, System.Types, System.UITypes, System.Classes, System.Variants,
  FMX.Types, FMX.Controls, FMX.Forms, FMX.Graphics, FMX.Dialogs, FMX.Objects,
  iPub.FMX.SystemBars;

type
  TForm1 = class(TForm)
    rctStatusBar: TRectangle;
    rctNavigationBar: TRectangle;
    rctGestureBar: TRectangle;
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
    procedure SystemBarsInsetsChange(Sender: TObject);
  protected
    function HasBottomContent: Boolean; virtual;
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.fmx}

procedure TForm1.FormCreate(Sender: TObject);
begin
  SystemBars.StatusBarBackgroundColor := $00FFFFFF; // Branco transparente (forçando os ícones escuros)
  SystemBars.NavigationBarBackgroundColor := $00FFFFFF; // Branco transparente (forçando os ícones escuros)
  SystemBars.Visibility := TFormSystemStatusBar.TVisibilityMode.VisibleAndOverlap;
  SystemBars.OnInsetsChange := SystemBarsInsetsChange;
  SystemBarsInsetsChange(nil);
end;

function TForm1.HasBottomContent: Boolean;
begin
  // Mude o retorno para True caso tenha algum controle alinhado na parte de baixo, como um botão.
  Result := False;
end;

procedure TForm1.SystemBarsInsetsChange(Sender: TObject);
begin
  rctStatusBar.Height := Self.SystemBars.Insets.Top;
  rctNavigationBar.Height := Self.SystemBars.TappableInsets.Bottom;
  if HasBottomContent then
    rctGestureBar.Height := Self.SystemBars.Insets.Bottom - Self.SystemBars.TappableInsets.Bottom
  else
    rctGestureBar.Height := 0;
end;

end.
```

O .fmx do form:
```pascal
object Form1: TForm1
  Left = 0
  Top = 0
  ClientHeight = 604
  ClientWidth = 360
  OnCreate = FormCreate
  object rctStatusBar: TRectangle
    Align = MostTop
    Size.Height = 0.000000000000000000
    Size.PlatformDefault = False
  end
  object rctNavigationBar: TRectangle
    Align = MostBottom
    Size.Height = 0.000000000000000000
    Size.PlatformDefault = False
  end
  object rctGestureBar: TRectangle
    Align = MostBottom
    Size.Height = 0.000000000000000000
    Size.PlatformDefault = False
  end
end
```

**Comment by viniciusfbb** [comment]
Alisson, conseguiu resolver?

**Comment by alissonrodrigo** [comment]
Ainda não pude testar... mas hoje pela manha te dou um feedback

**Comment by alissonrodrigo** [comment]
![image](https://user-images.githubusercontent.com/8572209/151220657-b112ca49-bfc9-4e97-9c0b-d1727316ec8b.jpeg)

Boa tarde deu certo, agora só não entendi o porque uso de 3 elementos para ajustes já que o Android 2! Barra de notificação e informações e navegação!

**Comment by viniciusfbb** [comment]
Sim, você pode substituir o rctNavigationBar e rctGestureBar por apenas 1, que poderia se chamar rctBottomBar por exemplo. Esse foi um exemplo de como transformar as informações do SystemBars.Insets e SystemBars.TappableInsets em margens para o seu layout.

Só esclarecendo as nomenclaturas:
![image](https://user-images.githubusercontent.com/11139086/151278879-f1f8f9b1-8aa3-4ad6-82f6-fe3d5336562b.png)
![image](https://user-images.githubusercontent.com/11139086/151278896-69c3c5fc-8034-4176-8da8-7148b4659724.png)

Nas configurações do seu android provavelmente terá a opção de alterar o celular para GestureBar:

![Screenshot_20220126-222719](https://user-images.githubusercontent.com/11139086/151278943-80be35e0-c771-4437-a8e4-5477acc40772.png)

**Comment by viniciusfbb** [comment]
Obs: usei o retângulo alinhado Bottom no exemplo pq considerei aplicação que permite apenas modo retrato. No modo paisagem, o NavigationBar pode ir para as laterais da tela, ou até continuar na parte de baixo, varia de device pra device. Os insets retornam sempre os valores corretos. Você poderia adaptar o código da seguinte forma:

```pascal
procedure TForm1.SystemBarsInsetsChange(Sender: TObject);
begin
  rctStatusBar.Height := Self.SystemBars.Insets.Top;
  if HasBottomContent then
    rctBottomBar.Height := Self.SystemBars.Insets.Bottom
  else
    rctBottomBar.Height := Self.SystemBars.TappableInsets.Bottom;
end;
```

**Comment by viniciusfbb** [comment]
Obs: usei o retângulo alinhado Bottom no exemplo pq considerei aplicação que permite apenas modo retrato. No modo paisagem, o NavigationBar pode ir para as laterais da tela, ou até continuar na parte de baixo, varia de device pra device. Os insets retornam sempre os valores corretos. Você poderia adaptar o código da seguinte forma:

```pascal
procedure TForm1.SystemBarsInsetsChange(Sender: TObject);
begin
  rctStatusBar.Height := Self.SystemBars.Insets.Top;
  if HasBottomContent then
    rctBottomBar.Height := Self.SystemBars.Insets.Bottom
  else
    rctBottomBar.Height := Self.SystemBars.TappableInsets.Bottom;
  Padding.Left := Self.SystemBars.TappableInsets.Left;
  Padding.Right := Self.SystemBars.TappableInsets.Right;
end;
```

**Comment by alissonrodrigo** [comment]
Bom dia, entendi o Gesturebar e basicamente igual o do iOS, não tenho nenhum aparelho Android com esse recurso... Mas valeu pela dia e pela biblioteca.
Quando tiver novidades sobre o Skia 3 notifica a comunidade.
